# Generated by Django 5.2.2 on 2026-05-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('image', models.ImageField(upload_to='images/products', verbose_name='تصویر محصول')),
                ('short_description', models.CharField(max_length=300, null=True, verbose_name='توضیحات محصول')),
                ('is_active', models.BooleanField(verbose_name='موجود/غیرموجود')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
