# Generated by Django 5.2.2 on 2026-07-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='پرطرفدار'),
            preserve_default=False,
        ),
    ]
