# Generated by Django 5.2.2 on 2026-06-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_alter_order_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قمیت نهایی تک محصول'),
        ),
    ]
