# Generated by Django 5.2.2 on 2026-05-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی فوتر',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/site_setting', verbose_name='لوگو سایت')),
                ('url', models.URLField(verbose_name='نشانی سایت')),
                ('phone', models.CharField(blank=True, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('introduction_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='معرفی سایت')),
                ('about_us_text', models.TextField(blank=True, null=True, verbose_name='متن درباره\u200cی ما')),
                ('intro_image', models.ImageField(null=True, upload_to='images/site_setting', verbose_name='تصویر معرفی سایت')),
                ('copy_right', models.TextField(max_length=500, verbose_name='متن کپی\u200cرایت')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اسلایدر')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('image', models.ImageField(upload_to='images/sliders', verbose_name='تصویر اسلایدر')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='آدرس شعبه')),
                ('website', models.URLField(verbose_name='وبسایت شعبه')),
                ('phone', models.CharField(null=True, verbose_name='شماره تماس شعبه')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_module.footercat', verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک\u200cها',
            },
        ),
    ]
