# Generated by Django 5.2.2 on 2026-07-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(default='tehran', max_length=100, verbose_name='آدرس'),
            preserve_default=False,
        ),
    ]
