# Generated by Django 5.2.2 on 2026-07-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_sitesetting_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(max_length=100, verbose_name='آدرس شعبه اصلی'),
        ),
    ]
